
export const data = {

}

export const TemplateData = [{
    TableData: [
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "冲丝",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 0.0,
            "stageName": "冲丝",
            "processName": "冲丝",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 100.000,
            "passQty": 90.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "泡桐",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 1.0,
            "stageName": "泡桐",
            "processName": "泡桐",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 100.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 2.0,
            "stageName": "磨床",
            "processName": "粗磨",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 100.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 3.0,
            "stageName": "磨床",
            "processName": "半精磨",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 50.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 3.0,
            "stageName": "磨床",
            "processName": "半精磨",
            "stationName": "--",
            "userAccount": "1002",
            "userName": "赵云",
            "dispQty": 50.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 4.0,
            "stageName": "磨床",
            "processName": "精磨",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "化镀",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 5.0,
            "stageName": "化镀",
            "processName": "化镀",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        }
    ],
    日期: "xxx",
    生产单: "xxx",
    总数量: "xxx",
    料号: "xxx",
    品名: "xxx",
    物料规格: "xxx",
},
{
    TableData: [
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "冲丝",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 0.0,
            "stageName": "冲丝",
            "processName": "冲丝",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 100.000,
            "passQty": 90.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "泡桐",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 1.0,
            "stageName": "泡桐",
            "processName": "泡桐",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 100.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 2.0,
            "stageName": "磨床",
            "processName": "粗磨",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 100.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 3.0,
            "stageName": "磨床",
            "processName": "半精磨",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 50.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 3.0,
            "stageName": "磨床",
            "processName": "半精磨",
            "stationName": "--",
            "userAccount": "1002",
            "userName": "赵云",
            "dispQty": 50.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 4.0,
            "stageName": "磨床",
            "processName": "精磨",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "化镀",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 5.0,
            "stageName": "化镀",
            "processName": "化镀",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        }
    ],
    日期: "xxx",
    生产单: "xxx",
    总数量: "xxx",
    料号: "xxx",
    品名: "xxx",
    物料规格: "xxx",
}]

export const TemplateData2 = {
    TableData: [
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "冲丝",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 0.0,
            "stageName": "冲丝",
            "processName": "冲丝",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 100.000,
            "passQty": 90.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "泡桐",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 1.0,
            "stageName": "泡桐",
            "processName": "泡桐",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 100.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 2.0,
            "stageName": "磨床",
            "processName": "粗磨",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 100.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 3.0,
            "stageName": "磨床",
            "processName": "半精磨",
            "stationName": "--",
            "userAccount": "0001",
            "userName": "小程序管理员",
            "dispQty": 50.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 3.0,
            "stageName": "磨床",
            "processName": "半精磨",
            "stationName": "--",
            "userAccount": "1002",
            "userName": "赵云",
            "dispQty": 50.000,
            "passQty": 0.0,
            "startDate": "2023-07-22",
            "endDate": "2023-07-22"
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "磨床",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 4.0,
            "stageName": "磨床",
            "processName": "精磨",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "化镀",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 5.0,
            "stageName": "化镀",
            "processName": "化镀",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        },
        {
            "workorder": "K001-1510-230722043.1",
            "partNumber": "1001000005",
            "partName": "轴",
            "partDesc1": "轴 Φ4.65*53.31 SF010005",
            "targetQty": 100,
            "workorderStatus": "Initial",
            "urgentStatus": "Y",
            "salesorder": "K001-1510-230722043",
            "customerName": "意卡德",
            "salesCode": "",
            "custClass": "",
            "createDate": "2023-07-22",
            "imagePath": "",
            "availableQty": "100",
            "stage": "包装",
            "planQty": "100",
            "planInputDate": "2023-07-22",
            "planOutputDate": "2023-07-22",
            "stepno": 6.0,
            "stageName": "包装",
            "processName": "包装",
            "stationName": "--",
            "userAccount": null,
            "userName": null,
            "dispQty": null,
            "passQty": 0.0,
            "startDate": null,
            "endDate": null
        }
    ],
    日期: "xxx",
    生产单: "xxx",
    总数量: "xxx",
    料号: "xxx",
    品名: "xxx",
    物料规格: "xxx",
}


